# Generated by Django 5.0 on 2024-01-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stumentor',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='hobbies.mentor'),
        ),
    ]
