# Generated by Django 5.0 on 2024-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_alter_student_stumentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stumentor',
            field=models.CharField(blank=True, default='none', max_length=8, null=True),
        ),
    ]
