# Generated by Django 5.0 on 2024-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_alter_student_stumentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stumentor',
            field=models.CharField(default='none', max_length=8),
        ),
    ]
