# Generated by Django 5.0 on 2024-01-31 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_alter_student_stumentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stumentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.mentor'),
        ),
    ]
